# Generated by Django 4.0.5 on 2022-06-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_vencimiento', models.DateField()),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('datos_contacto', models.CharField(max_length=500)),
                ('detalles_oferta', models.CharField(max_length=500)),
            ],
        ),
    ]
